AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Cloudformation template'

Resources:
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'awazedCFN'
      ManagedPolicyArns:
        - 'arn:aws:iam:aws:policy/AdministratorAccess'